### PR TITLE
[Testing] Feed+Battle Reports

### PR DESCRIPTION
**Pull request by karllindmark**
@peter-budo 

Add tests for feed+battle reports. I decided to go the wrapper way (good idea Peter) as the code becomes less ugly and it's easier to maintain in the long run.

However, I only marked `fromJsonArray(...)` as deprecated in this PR, but deprecated items will be removed in a PR or so.

### CODE REVIEW

**Comment by karllindmark** [comment]
@peter-budo:

All tests in place! Test image

**Comment by peter-budo** [comment]
ROFL JUnit 3 naming `test....` We know we are doing testing. You may want to exchange it perhaps with `shouldDoABC` (this method should do something, but still it ma fail). Also with tests you can make methods names as long as you wish so for easier readability maybe following my example  :wink:

**Comment by karllindmark** [comment]
OK, method names changed. :-)

**Comment by karllindmark** [comment]
@peter-budo

**Pull request merged**
