### PR TITLE
Add a core soldier frame and setting up the menu to access it.

### PR DESCRIPTION
**Pull request by karllindmark**
Add a core soldier frame and setting up the menu to access it.

### CODE REVIEW

**Comment by karllindmark** [comment]
@peter-budo: Finally able to put up a PR. @stillesjo

**Comment by peter-budo** [comment]
Issues:
1. Statistics show in action bar next to icon `@string/app_name`
2. Flow back button going to starting screen fine, action bar should give me sliding menu not back button option (counter-intuitive navigation in my opinion)
3. Assignments icon some gibberish of different platforms, navigation action bar what I want to see in Statistics, back button closing app - broken navigation (same applies to Overview, News, Battle Feed, Notifications, Servers, View Forums, Saved Threads)
4. Unlocks - notification need to be discussed. In meantime read book Smashing Android UI pg. 120-136. Also I like how notifications works on Falcon Pro when sending new tweets
5. PROPOSAL - I would like to see "Logged in as" expandable/collapsable. Default behaviour collapse showing only text "Logged in as PLAYER_NAME" on the line click expand. That can also mean using text styling of this more in the line of "sub-menus" (overview, statistics, etc) OPEN FOR DISCUSSION so please tell me what you think

PS: I will comment on code in line as necessary

**Comment by karllindmark** [comment]
@peter-budo: What would happen upon clicking "Logged in as <PLAYER>"?

**Comment by peter-budo** [comment]
It would show what is currently there. I just think that section could be hidden to preserve space for other menu options and showed as optional thing. Any  thoughts about it?

**Comment by karllindmark** [comment]
@peter-budo: What if we didn't have the dropdown, just do a

LOGGED IN AS [LOGO] [NAME]? 

Takes up one regular row.

Any thoughts on this @stillesjo?

We could also do the

LOGGED IN AS [NAME] without the gravatar. How important is the gravatar?

**Comment by peter-budo** [comment]
Without logo please. Logo is actual space killer there for me. I though that giving you expandable option would keep both sides happy :wink:

**Comment by karllindmark** [comment]
@peter-budo: Ok, updated with just text at the top. Thoughts? Feels a bit off though.

**Comment by peter-budo** [comment]
@karllindmark I do not see any associated commit to it

**Comment by karllindmark** [comment]
@peter-budo: Haha, tired me forgot to push the commit. Grr. Here, have two complementary screenshots instead. This is the initial view:



This is what you see when you scroll, ie it has a given place at the top:

**Comment by peter-budo** [comment]
@karllindmark first image has broken link

**Comment by karllindmark** [comment]
See this instead @peter-budo: https://db.tt/WE1GqJqu

**Comment by peter-budo** [comment]
I think it is good for the moment. If we come up with some colour schema we can then apply it to name as to make it stand out little more. You have to take it that there is a majority of users that have single EA account so "logged as" is not important feature as seeing all soldiers you have on different platforms. I know only one guy that has multiple EA accounts for BF3

**Comment by karllindmark** [comment]
Good point. Might want to consider the fact that people might borrow
devices and such, but this might be suitable at the moment. It's not a list
item, so it will show at the top all the time.

**Comment by karllindmark** [comment]
@peter-budo: Pushed the commits now, try the new layout on your phone too. :-))

**Comment by karllindmark** [comment]
Re list of issues @peter-budo, added a few questions below (under the appropriate section);
- [x] ~~Statistics show in action bar next to icon @string/app_name~~
- [ ] Flow back button going to starting screen fine, action bar should give me sliding menu not back button option (counter-intuitive navigation in my opinion)
- [ ] ~~Assignments icon some gibberish of different platforms~~, navigation action bar what I want to see in Statistics, back button closing app - broken navigation (same applies to Overview, News, Battle Feed, Notifications, Servers, View Forums, Saved Threads)

## 

Would you mind clarifying? Do you mean the following?
1. Statistics activity should be using the ActionBar navigation mode that's a list? In other words, filter the display via ActionBar?
2. Back button should return to the base fragment (BattleFeedFragment), and it should also be the default one you see?

## 
- [ ] Unlocks - notification need to be discussed. In meantime read book Smashing Android UI pg. 120-136. Also I like how notifications works on Falcon Pro when sending new tweets

## 

When you say notification, I reckon you mean the Toast? I'll have to check out SA-UI. :-)

## 
- [x] ~~PROPOSAL - I would like to see "Logged in as" expandable/collapsable. Default behaviour collapse showing only text "Logged in as PLAYER_NAME" on the line click expand. That can also mean using text styling of this more in the line of "sub-menus" (overview, statistics, etc) OPEN FOR DISCUSSION so please tell me what you think~~

**Pull request merged**
