### PR TITLE
Image densities

### PR DESCRIPTION
**Pull request by peter-budo**
@karllindmark this is just temporary pull request

 • Updated Android target sdk to 5.0 and build tools to 21.0.1
 • Density images provided for weapon & vehicle statistics, unlocks, assignments and awards (medals only)

Have go and let me know what you think

My observations:
 • Weapons, vehicles looks good
 • Unlocks image size is good but layout need update to get check/tick sign I guess above right of unlock item
 • Assignments and awards looks good but large so I suggest resizing. According to dimensions from layout it was set to 142dpi. As this is little irregular size I used 144dp, which makes mdpi as 144px, hdpi as 216px, xhdpi as 288px and xxhdpi as 432px. The other layouts are using with of 128dpi so I can try to use this on awards and assignments.

### CODE REVIEW

**Comment by karllindmark** [comment]
By the way: http://puu.sh/cmlex/d9cec8b444.png :-))

**Comment by peter-budo** [comment]
And what is your point?

**Comment by karllindmark** [comment]
I just saw the number of changed files, looked a bit fun!

**Comment by peter-budo** [comment]
@karllindmark give it a go. It does play much better on Samsung devices that I have at hand. I left ribbons unchanged, for the moment. If necessary we can always resize them later

**Comment by karllindmark** [comment]
Good job @peter-budo! The biggest difference I'm noticing is that assignment doesn't lag a single bit when being opened. :-))

If you're done, feel free to merge it.

**Pull request merged**
