### PR TITLE
Add functionality to detect sw600dp and sw720dp

### PR DESCRIPTION
**Pull request by karllindmark**
@peter-budo 

Do we want to have the variable+getters in our `Bf4Intel` application class instead, so that it's only available in one place?

Pros? Cons?

Right now I'm making sure that `sw720dp` _isn't_ `sw600dp` - do we want that behavior, or should `sw720dp` devices report that they're `sw600dp` too (programmatically)?

### CODE REVIEW

**Comment by karllindmark** [comment]
@peter-budo: Big "WTF" on that Travis CI error

**Comment by peter-budo** [comment]
@karllindmark would you mind attach just sample activity and dialog to lets say awards adapter and just show text in them "activity | dialog" when we click on award?

**Comment by karllindmark** [comment]
@peter-budo I'll get on it later this evening, as I'm not by my computer at the moment :-)

**Comment by karllindmark** [comment]
@peter-budo: If you click on an award now in this PR, it'll take you to a new activity if you're on Nexus 5/Nexus 7, but show a dialog when on a `sw720dp`. :-)

**Comment by karllindmark** [comment]
@peter-budo: Feel free to merge this so that we can get going with the details. :+1:

**Pull request merged**
