### PR TITLE
Minor inspection run

### PR DESCRIPTION
**Pull request by karllindmark**
I ran the inspector plugin in Android Studio and fixed some errors.

### CODE REVIEW

**Comment by karllindmark** [comment]
@peter-budo: Merge if you consider it OK.

**Comment by peter-budo** [comment]
I should be available on skype late in the afternoon  if you need something, morning will be some shopping.

**Comment by karllindmark** [comment]
@peter-budo: Updated the pull request, will address adapter complexity on the road. Don't merge yet. :-)

**Comment by karllindmark** [comment]
@peter-budo: Refactoring done. Let me know what you think.

**Pull request merged**
