### PR TITLE
Update rank images to have correct alpha (phew)

### PR DESCRIPTION
**Pull request by karllindmark**
@peter-budo 

Looks good?

### CODE REVIEW

**Comment by peter-budo** [comment]
Now explain why you didn't reused original pull request?

**Comment by karllindmark** [comment]
I'm not quite sure. I can go back and fix that if you like. A bit mushy
after too much hopping between ClearCase and Git today.

**Comment by karllindmark** [comment]
@peter-budo: Fixed, I merged your pull request - now we have yours as base in this one.

**Comment by peter-budo** [comment]
You didn't have to, I just wanted to know what happen...

**Pull request merged**
