### PR TITLE
Pull to refresh implementation

### PR DESCRIPTION
**Pull request by karllindmark**
Rebased, adjusted and reworked a bit (replaces #145)...

In other words, a "pull to refresh" implementation.

@peter-budo

### CODE REVIEW

**Comment by karllindmark** [comment]
Known issues:
- [ ] The detailed stats fragment isn't technically a regular ListView, so it becomes a bit sad (try swiping back up). I filed an issue towards emilsjolander/StickyListHeaders#325, but we might need to resort to [a workaround](http://stackoverflow.com/questions/23053799/scrollup-not-working-in-stickylistviewheader-with-swiperefreshlayout) in the meantime (while waiting for that official fix).

**Comment by peter-budo** [comment]
I been playing with this PR and here are some thinks I seen
• sometime only colour changing strip is showed or the opposite colour changing logo, example fresh install, select account and you are move to overview where both loading strip and colour changing logo do show up. Open Assignments and only colour changing logo is displayed no loading strip. Open statistics to start weapon stats loading both items showed. Unlocks, colour changing logo showed and once that disappears loading strip shows briefly 
• loading strips not being dismissed this is I believe down to our dodgy implementation of battlereports

**Comment by karllindmark** [comment]
- [x] Remove loading stripe when Battle reports have been refreshed.
- [x] Update to match dev without `StickyListHeaders`
- [x] Try darker colors from Battlelog

**Comment by karllindmark** [comment]
@peter-budo: OK, changes are in now. :-)

**Comment by peter-budo** [comment]
@karllindmark not up-to-date with dev also no marked as done on pivotal. Someone forgetting basics!!! :wink:

**Pull request merged**
