### PR TITLE
Fixing issues with the NavigationDrawer

### PR DESCRIPTION
**Pull request by karllindmark**
Issues:

Fixed in 58abb7e:
Item persistence upon screen rotation
Item selection working upon screen rotation

### CODE REVIEW

**Comment by karllindmark** [comment]
Hiya @peter-budo, give it a go!

Steps you _gotta_ try:
1. Open SlidingMenu
2. Select Overview
3. Rotate device
4. Note that Overview is still selected
5. Select Forums > View Forums
6. Note that it's displaying the forums
7. Rotate device again
8. Note that Forums > View Forums is still selected
9. Press Overview again
10. Note that content changes
11. Profit?

**Comment by peter-budo** [comment]
Whats up with all these deleted files?

**Comment by karllindmark** [comment]
Temporary build files that we don't wanna version control. :-) @peter_budo

**Comment by karllindmark** [comment]
[10:31:01] @peter-budo: clicking on AB icon does not open naw drawer
[10:32:09] @peter-budo: touch to scroll to open drawer is too close to edge so hard to drag it
- [x] Action Bar icon doesn't open navigation drawer
- [ ] The edge swapping is very close to edge so on phone with protector that rises sides it that push finger deeper in screen and harder to invoke scrolling to open drawer

**Pull request merged**
